version: '3.8'
services:
  api:
    build:
      dockerfile: dockerfile
    ports:
      - '8001:4001'
    depends_on:
      - postgres
    env_file:
      - docker.env
  postgres:
    image: postgres:14.2
    ports:
      - '5432:5432'
    env_file:
      - docker.env
